version: 2
jobs:
  build:
    docker:
      - image: framgia/laravel-workspace
      - image: mysql:5.7
        environment:
          MYSQL_HOST: 127.0.0.1
          MYSQL_DATABASE: demo
          MYSQL_USER: demo
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: root
    steps:
      - checkout
      - run: cp .env.example .env
      # composer cache
      - restore_cache:
          keys:
            - vendor-v1-{{ checksum "composer.lock" }}ắt
      - run:  composer install
      - save_cache:
          key: vendor-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      # run test
      - run: php artisan key:generate
      - run: framgia-ci run --local
      - run: framgia-ci test-connect 127.0.0.1 3306 60
      - run: php artisan migrate
